# Path to load models library
model:  "/journel/s0/zur74/cpgan/cpgan/eval/models_lib"

# PATH to load different images data
img_path:
  img_large:  "/journel/s0/zur74/data/ibm-11/raw"
  img_demo:  "/journel/s0/zur74/data/ibm-11/example"
  img_chunk:  "/journel/s0/zur74/data/ibm-11/Berea-sub"

# PATH to load simulation results
feature_path: "/journel/s0/zur74/cpgan/cpgan/features/data"

# PATH to save models history 
trainhist_path: "/journel/s0/zur74/cpgan/cpgan/train/train_hist"