name: porousgan
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - numpy=1.20.3
  - numpy-base=1.20.3
  - openpnm=2.8.2
  - pip
  - python=3.8
  - scikit-image=0.18.3
  - scipy=1.7.1
  - pip:
    - porespy==1.3.1